name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Check for outdated packages
      run: |
        echo "Checking for outdated packages..."
        npm outdated || true
        
        echo "Current package versions:"
        npm list --depth=0

    - name: Update package-lock.json
      run: |
        echo "Updating package-lock.json..."
        npm update
        
    - name: Run security audit
      run: |
        echo "Running security audit..."
        npm audit || true
        
        echo "Attempting to fix vulnerabilities..."
        npm audit fix || true

    - name: Test build after updates
      run: |
        echo "Testing build with updated dependencies..."
        npm run build:11ty
        npm run build:js
        
        echo "Build test successful"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Weekly Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates:
          
          ### Changes
          - Updated `package-lock.json` with latest compatible versions
          - Fixed security vulnerabilities (if any)
          - Verified build compatibility
          
          ### Testing
          - Build test passed
          - No breaking changes detected
          
          ### Review Checklist
          - [ ] Review updated dependencies
          - [ ] Test functionality in preview
          - [ ] Merge if all checks pass
          
          ---
          *This PR was automatically generated by GitHub Actions*
        branch: dependency-updates
        delete-branch: true
